### ISSUE TITLE
Can't run gradle

### ISSUE THREAD

**Issue by SemenMartynov** [AleksanderBoldyrev/JSON_Val#11]
```
$ ./gradlew build
Error: Could not find or load main class org.gradle.wrapper.GradleWrapperMain
```

This is the case when you have to have a small jar file in the repository.
It downloads and starts the gradle service.
You need to put it into the `gradle/wrapper` folder.

And it seems to me that in the folder `ValidatingService_gradle` you have some rubbish.

**Comment by AleksanderBoldyrev** [comment]
e6542e05a3a4463dbddbaf0695754878b9fb0ba5

**Comment by SemenMartynov** [comment]
Check the `ValidatingService_gradle` folder!
