### ISSUE TITLE
JavaDoc

### ISSUE THREAD

**Issue by SemenMartynov** [AleksanderBoldyrev/JSON_Val#2]
Provide JavaDoc to your code

**Comment by AleksanderBoldyrev** [comment]
Main functions are provided with JavaDoc

**Comment by AleksanderBoldyrev** [comment]
Could you change my surname in the list, please?

**Comment by AleksanderBoldyrev** [comment]
BOldyrev, not BAldyrev

**Comment by SemenMartynov** [comment]
Use branches for feature implementation and don'e forget to link issues with commits.
